### ISSUE TITLE
Include more information in the log files

### ISSUE THREAD

**Issue by atenart** [retis-org/retis#179]
We currently only have events in the log file after collection, but we should include more data for post-processing. This data could be for example the dumped nft configuration so we can match rules from the config to events to post-processing time. A format could look like:

```json
{
  "cmd": { "retis", "collect", "-c", "skb" },
  "modules": {
     "nft": {
        ...
     },
  "events": {
     { ... },
     { ... },
  },
}
```

As a first step we should include the command that was used while collecting events & what probes and collectors where used (as this is not fully expressed by the command). Also not only the `collect` command can write a log file, so we might want to either convey the info in those commands or even add more.

**Comment by amorenoz** [comment]
> Also we should include retis version.

And leave space for runtime information such as UTC time as discussed in #299

**Comment by liuhangbin** [comment]
@amorenoz @atenart Hi, I saw the current JSON output looks like what is described in [src/core/events/events.rs](https://github.com/retis-org/retis/blob/main/src/core/events/events.rs). Where should we put the timestamp of UTC <-> MONOTONIC time relationship? Should we move the `common` part out of `events`? Something like

```json
{
  "cmd": { "retis", "collect", "-c", "skb" },
  "common" { "task": {...}, "timestamp": {...}, "utc_adjust": {...} },
  "modules": {
     "nft": {
        ...
     },
  "events": {
     { ... },
     { ... },
  },
}
```

**Comment by atenart** [comment]
> @amorenoz @atenart Hi, I saw the current JSON output looks like what is described in [src/core/events/events.rs](https://github.com/retis-org/retis/blob/main/src/core/events/events.rs). Where should we put the timestamp of UTC <-> MONOTONIC time relationship? Should we move the `common` part out of `events`? Something like

No, `common` is an event sub-section containing keys shared by all events. But the actual value of the `common` sub-section depends on each event, so it can't be factorized.

But I think your proposal is close to what the output should look like: the current content under a new `events` key, and then additional keys to store specific data, such as `cmd`. Something like:

```json
{
  "cmd": { "retis", "collect", "-c", "skb" },
  "utc_adjust": "...",
  "modules": {
     "nft": {
        ...
     },
  },
  "events": {
     { ... },
     { ... },
  },
}
```

**Comment by liuhangbin** [comment]
> No, `common` is an event sub-section containing keys shared by all events. But the actual value of the `common` sub-section depends on each event, so it can't be factorized.
> 
> But I think your proposal is close to what the output should look like: the current content under a new `events` key, and then additional keys to store specific data, such as `cmd`. Something like:

Got it, thanks!

**Comment by atenart** [comment]
IMO the hard part will be how to properly design an API for various parts of Retis (eg. modules) to include a specific key/value in the JSON output. Feel free to include a design proposal here (or an RFC) PR if you want to discuss before diving too much into the implementation.

**Comment by liuhangbin** [comment]
> Feel free to include a design proposal here (or an RFC) PR if you want to discuss before diving too much into the implementation.

Sure, I will. But before that, I plan to resolve PR #329 first.

**Comment by liuhangbin** [comment]
@atenart Hi, I just back from PTO and got a lot of other user space tools works. So I may not have time to check it this month. Please feel free to keep working on it since you have done some works.
