### ISSUE TITLE
collect errors out with "Error: invalid digit found in string"

### ISSUE THREAD

**Issue by pspacek** [retis-org/retis#241]
###  Summary
`tools/retis_in_container.sh collect` errors out with "Error: invalid digit found in string"

### Environment
* kernel 6.4.12-arch1-1
* Docker container: quay.io/retis/retis 4333f006997c
* docker on the host: 1:24.0.5-1
* host is Arch Linux on x86_64 updated as of 2023-08-28

### Steps to reproduce
* `tools/retis_in_container.sh collect`

### Output
```console
Error: invalid digit found in string
```

I've tried to add `--log-level debug` but it does not extend the output.

I'm at loss what else to provide, but I'm happy to add more info if you tell me what's needed.

**Comment by pspacek** [comment]
I have big trouble debugging this using GDB or LLDB because GDB crashes on me constantly, and LLDB does not show me the right level of detail (but I admit I'm using it for the first time ...).

Anyway, I sense this might have something to do with Inspector constructor.

Content of `/etc/os-release` on my system:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

parse_os_info() returns:
```Ok Some("arch"), None```

**Comment by amorenoz** [comment]
@pspacek Thanks for reporting and for the initial analysis.
Indeed, it seems the kernel version convention used in Arch is not being parsed properly.

**Comment by amorenoz** [comment]
Still trying to figure out if this is the right solution, but in the time being, could you please check if this fixes your issue?
https://github.com/retis-org/retis/pull/242
