### ISSUE TITLE
Not all tests are run due to cli::cli::tests::cli_build exiting

### ISSUE THREAD

**Issue by atenart** [retis-org/retis#259]
Commit 3c651d75f971 ("cli: fix error messages on --help and --version") introduced an issue due to a side effect: instead of allowing us to catch errors being returned by `try_get_matches_from` and handling the exit, it made us rely on `clap` to do so. The issue is test `cli::cli::tests::cli_build` takes advantage of the above to check the help is correctly handled, which is now broken and the whole test suite is stopped when `clap` handles the help message.

A quick way to test this is to run `retis test cli::cli::tests::cli_build`, the output is currently

```
running 1 test
Trace packets on the Linux kernel

retis is a tool for capturing networking-related events from the system using ebpf and analyzing them.

Usage: retis [OPTIONS] <COMMAND>

Commands:
  sub1  does some things
  sub2  sub2 help
  help  Print this message or the help of the given subcommand(s)

Options:
      --log-level <LOG_LEVEL>
          Log level
          
          [default: info]
          [possible values: error, warn, info, debug]

  -p, --profile <PROFILE>
          Comma separated list of profile names to apply

      --kconf <KCONF>
          Path to kernel configuration (e.g. /boot/config-6.3.8-200.fc38.x86_64; default: auto-detect)

  -h, --help
          Print help (see a summary with '-h')

  -V, --version
          Print version
```

intead of

```
running 1 test
test cli::cli::tests::cli_build ... ok
```

**Comment by amorenoz** [comment]
ouch! didn't the CI run on that PR?
