### ISSUE TITLE
Add a command to inspect some parts of the running system

### ISSUE THREAD

**Issue by atenart** [retis-org/retis#285]
At least we should allow to list functions and tracepoints we can attach to. Currently the user has to guess.

Something like:
```
$ retis inspect --probe kprobe:* --probe tp:skb:*
...
```

**Comment by vlrpl** [comment]
I think there are ways to do this without the tool. Maybe we might want to consider adding some notes in the doc if "reliable enough"?

tp:
`find /sys/kernel/debug/tracing/events -type d`

available kprobes:
`/proc/kallsyms`

**Comment by vlrpl** [comment]
> > I think there are ways to do this without the tool. Maybe we might want to consider adding some notes in the doc if "reliable enough"?
> 
> We could, with the following remarks.
> 
> > tp: `find /sys/kernel/debug/tracing/events -type d`
> 
> For tp this is not so easy, there are different kinds of events and no everything reported is a tp. We do have the same issue in Retis atm (#293).
> 

yep. Of course, that should include the constraints

> > available kprobes: `/proc/kallsyms`
> 
> (nit: that would be `/sys/kernel/debug/tracing/available_filter_functions`)
> 

of course, kallsyms is a bit simplified.

> For kprobes that should work better, there are a few entries to filter (`isra` ones) but that's only some "noise".

In general, people tend to not read the doc, so a value in a command might still make sense.
The idea is to consider some potential alternatives if any acceptable is available.
