### ISSUE TITLE
Show timestamps in human-readable format

### ISSUE THREAD

**Issue by amorenoz** [retis-org/retis#299]
Currently, events show a CLOCK_MONOTONIC timestamp which is good to compare events and calculate latencies but it's not very human readable.

The proposal is to be able to print a HHMMSS.MS time in events.

For that, we'd need to get the UTC <-> MONOTONIC time relationship at startup and store it in the event file. So we need some room for metadata at the beginning of the file (which is also useful for other things).

**Comment by liuhangbin** [comment]
@amorenoz FYI, I will be looking into this issue next week. Please tell me if you already started. Thanks!

**Comment by atenart** [comment]
@liuhangbin it's safe to assume @amorenoz hasn't started looking into this, feel free to take it.

> For that, we'd need to get the UTC <-> MONOTONIC time relationship at startup and store it in the event file. So we need some room for metadata at the beginning of the file (which is also useful for other things).

Also FYI the above description is tracked in issue #179; which should be tackled first. Feel free to discuss the overall design before implementing all the details if you choose to take this.

**Comment by amorenoz** [comment]
Correct, I haven't started with this :-/

**Comment by atenart** [comment]
This is done.
