### ISSUE TITLE
Auto-collector mode fails to detect nft requirement mismatch

### ISSUE THREAD

**Issue by atenart** [retis-org/retis#322]
Seen on 8.4 but could be seen on other distros.

```
Error: Could not initialize the Nft collector: No type linked to name __nft_trace_packet
```

This looks like `Symbol::from_name()` call succeed in `can_run` but later use of the symbol in `init` fails as BTF information cannot be found. This could affect other modules too.

One solution would be to improve the check in `can_run` to use BTF inspection directly; but this might hide another issue if a probe is found to be valid in sysfs but no BTF info can be found. It might also be related to the btf-rs issue with strings.

**Comment by vlrpl** [comment]
> As discussed offline, one option is to let the user provide the BTF files for those missing modules; or to have an automatic way to do this. In any way, `can_run` should detect this and bail out.

The BTF part is related to #72
