### ISSUE TITLE
retis on aarch64

### ISSUE THREAD

**Issue by vlrpl** [retis-org/retis#373]
It would be nice to have Retis (at least) [cross-]compile on arm.

What's needed:
1. split the single `vmlinux.h` logic into `vmlinux-x86_64.h` and `vmlinux-aarch64.h` (for arch-dependent data access, e.g. `pt_regs`). Essentially, this requires to generate a new vmlinux.h for arm64
2. `vmlinux.h` that pulls the arch-specific `vmlinux*.h` depending on `__TARGET_ARCH_*`
3. [optional] This could be a good chance to reshape our vmlinux.h (unnecessarily bloated)
5. [optional] Ideally, CI with functional tests

**Comment by atenart** [comment]
Done in #379.
