### ISSUE TITLE
Failed to parse section Ovs: Unsupported action id 24

### ISSUE THREAD

**Issue by igsilya** [retis-org/retis#398]
Looks like `OVS_ACTION_ATTR_DROP` is not supported.

Also, there seems to be a fundamental issue with the kernel-only `OVS_ACTION_ATTR_SET_TO_MASKED` that is not actually part of uAPI and so can have different values depending on how many actions the running kernel supports.  But, I guess, it shouldn't be used that often, so maybe not a big problem.

**Comment by amorenoz** [comment]
Yes, `OVS_ACTION_ATTR_SET_TO_MASKED` is indeed problematic. I chose to only display "set_masked" and try our best to display the internal field to try to avoid the user the internal-only noise.
