### ISSUE TITLE
Consider automatic mounting of debugfs if not present

### ISSUE THREAD

**Issue by igsilya** [retis-org/retis#402]
It is painful to manage debugfs mounts in network namespaces, because the mount only exists for the duration of the `ip netns exec`, i.e. if you run `ip netns exec <my-ns> mount -t debugfs debugfs /sys/kernel/debug`, it will not be mounted while running `ip netns exec <my-ns> retis collect` right after.  This can be worked around by executing the shell and both commands inside, but If retis could mount it for us, it would be much easier.

Can be an opt-in behavior.

**Comment by igsilya** [comment]
The problem is that I'm running it from the application that already runs inside the namespace.  So, I just don't want to add the mounting command to the application, if possible.  It's not a deal breaker, but it would be nice to have this functionality.

**Comment by atenart** [comment]
Maybe we could do this under `--allow-system-changes`?

**Comment by igsilya** [comment]
> Maybe we could do this under `--allow-system-changes`?

Sounds reasonable.
