### ISSUE TITLE
Add a contributing doc

### ISSUE THREAD

**Issue by atenart** [retis-org/retis#48]
Could be in `CONTRIBUTING.md` and should contain pointers on how to contribute, what to check before the CI does, etc. Another aspect would be to write a small example (with explanations) on how to write a collector.

Please drop below raw information that should be part of it.

**Comment by amorenoz** [comment]
Maybe we could add coding style conventions such as "group `mod` and `use` separately"
```
mod sub1;
mod sub2;

use sub1::something;
use sub2::*
```

**Comment by amorenoz** [comment]
Also, add C coding style for ebpf hooks (e.g: linux style)

**Comment by vlrpl** [comment]
document and adopt [safety comment](https://std-dev-guide.rust-lang.org/documentation/safety-comments.html).
This could also be enforced by [Clippy's undocumented_unsafe_blocks](https://rust-lang.github.io/rust-clippy/master/#undocumented_unsafe_blocks).
