### ISSUE TITLE
add bash completion script

### ISSUE THREAD

**Issue by vlrpl** [retis-org/retis#68]
There's a chance we'll end up having a decent number of options and adding a bash completion file could be a nice to have

**Comment by liuhangbin** [comment]
Hi @vlrpl @atenart 

I checked this feature. clap_complete has 3 ways to generate the shell completion.

The 1st way is using [generate_to](https://docs.rs/clap_complete/4.4.6/clap_complete/generator/fn.generate_to.html), which will generate the shell completion file at compile time. With this way we need to put the generator in `build.rs`.  But this way is very hard to implement as we need to `include!(src/cli/cli.rs)`, which also depends on a lot of modules.

The 2nd way is using [generate](https://docs.rs/clap_complete/4.4.6/clap_complete/generator/fn.generate.html), which could generate the completions file for a specified shell at runtime. But we need to add a `generate` parameter. e.g.
```Bash
# retis -h

Usage: retis [OPTIONS] <COMMAND>

Commands:
  collect  Collect network events
  print    Print stored events to stdout
  sort     Sort stored events in series based on tracking id
  pcap     Generate a PCAP file from stored events
  profile  Manage Profiles

Options:
      --log-level <LOG_LEVEL>  Log level [default: info] [possible values: error, warn, info, debug, trace]
  -p, --profile <PROFILE>      Comma separated list of profile names to apply
      --kconf <KCONF>          Path to kernel configuration (e.g. /boot/config-6.3.8-200.fc38.x86_64; default: auto-detect)
  -g, --generate <generator>   [possible values: bash, elvish, fish, powershell, zsh]
  -h, --help                   Print help (see more with '--help')
  -V, --version                Print version

# retis -g bash > bash_complete
# source bash_complete
```

The 3rd way is using the [unstalbe dynamic](https://docs.rs/clap_complete/4.4.6/clap_complete/dynamic/index.html) feature. With this way we can hide the generate parameter and user will not see it normally. e.g.
```
# retis -h
A subcommand definition to `flatten` into your CLI

Usage: retis [OPTIONS] <COMMAND>

Commands:
  collect  Collect network events
  print    Print stored events to stdout
  sort     Sort stored events in series based on tracking id
  pcap     Generate a PCAP file from stored events
  profile  Manage Profiles

Options:
      --log-level <LOG_LEVEL>  Log level [default: info] [possible values: error, warn, info, debug, trace]
  -p, --profile <PROFILE>      Comma separated list of profile names to apply
      --kconf <KCONF>          Path to kernel configuration (e.g. /boot/config-6.3.8-200.fc38.x86_64; default: auto-detect)
  -h, --help                   Print help (see more with '--help')
  -V, --version                Print version

# retis complete -h
Register shell completions for this program

Usage: retis complete --shell <SHELL> --register <REGISTER> [-- <COMP_WORDS>...]

Options:
      --shell <SHELL>        Specify shell to complete for [possible values: bash, fish]
      --register <REGISTER>  Path to write completion-registration to
  -h, --help                 Print help (see more with '--help')

# retis complete --shell bash --register bash_complete
# source bash_complete
```

Note the 2nd way supports `bash, elvish, fish, powershell, zsh` while the 3rd way only supports `bash, fish`. So which way do you want? 

The other question is how to use the completion file after generating? We can't force user to source it every time. Should we add an alise file to source the completion file and execuate `retis` with all parameters ? e.g.

```
#!/bin/bash

source ${the_install_path}/shell_completion
retis $@
```

**Comment by liuhangbin** [comment]
> Do you know if this is unstable because not all shells are supported or because some features are not there yet?

From the maintainer's [comment](https://github.com/clap-rs/clap/discussions/5269#discussioncomment-7958786), the `dynamic completions` is still under development and will replace `static completions` in the future. So I'd suggest use this feature directly.

> Please, no. We should either install it as part of the rpm or in the container image, or let the user source it

OK, let's do it later. When the `dynamic completions` got stable. I think the completion file should be stable too as it doesn't depend on the parameter list. Here is an example file for bash completion.

```
_clap_complete_retis() {
    export IFS=$'\013'
    export _CLAP_COMPLETE_INDEX=${COMP_CWORD}
    export _CLAP_COMPLETE_COMP_TYPE=${COMP_TYPE}
    if compopt +o nospace 2> /dev/null; then
        export _CLAP_COMPLETE_SPACE=false
    else
        export _CLAP_COMPLETE_SPACE=true
    fi
    COMPREPLY=( $("retis" complete --shell bash -- "${COMP_WORDS[@]}") )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    elif [[ $SUPPRESS_SPACE == 1 ]] && [[ "${COMPREPLY-}" =~ [=/:]$ ]]; then
        compopt -o nospace
    fi
}
complete -o nospace -o bashdefault -F _clap_complete_retis retis

```
